version: '3.3'

services:
  elk:
    container_name: elk
    image: 'sebp/elk:670'
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
    environment:
      LOGSTASH_START: 0

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - '6379:6379'

  mongo:
    container_name: 'mongo'
    image: 'mongo'
    ports:
      - '27017:27017'

  nginx:
    container_name: 'cdn'
    image: 'nginx'
    volumes:
      - c:/public/:/usr/share/nginx/html
    ports:
      - '9000:80'

  devnews:
    container_name: 'devnews'
    image: 'stijak/devnews'
    ports:
      - '8080:8080'
