version: '3.3'

services:
  elk:
    container_name: elk
    image: 'sebp/elk:720'
    ports:
      - '5601:5601'
    environment:
      LOGSTASH_START: 0

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - '6379:6379'

  mongo:
    container_name: 'mongo'
    image: 'mongo'
    ports:
      - '27017:27017'

  cdn:
    container_name: 'cdn'
    image: 'nginx'
    volumes:
      - c:/public/:/usr/share/nginx/html
    ports:
      - '9000:80'

  backend:
    container_name: 'backend'
    image: 'stijaktech/backend'
    volumes:
      - c:/public/:/public
    ports:
      - '8080:8080'

  frontend:
    container_name: 'frontend'
    image: 'stijaktech/frontend'
    ports:
      - '4200:80'
