apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eu.gcr.io/nifty-analyst-317516/mscode/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: cdn
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          volumeMounts:
            - mountPath: /public
              name: public
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7777
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7777
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: public
          hostPath:
            path: /home/marko_stijak_dev/application/public
      restartPolicy: Always
  selector:
    matchLabels:
      app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
