apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: virtual-host-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: 'https://www.devnews.xyz'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'devnews.xyz' ) {
        rewrite ^ https://www.$host$request_uri permanent;
      }
spec:
  tls:
    - secretName: devnews-xyz-tls
      hosts:
        - 'devnews.xyz'
        - 'www.devnews.xyz'
        - 'api.devnews.xyz'
        - 'cdn.devnews.xyz'
        - 'kibana.devnews.xyz'
  rules:
    - host: 'devnews.xyz'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 8080
    - host: 'www.devnews.xyz'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 8080
    - host: 'api.devnews.xyz'
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 8080
    - host: 'cdn.devnews.xyz'
      http:
        paths:
          - backend:
              serviceName: cdn
              servicePort: 8080
    - host: 'kibana.devnews.xyz'
      http:
        paths:
          - backend:
              serviceName: elk
              servicePort: 5601
