apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: virtual-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: 'https://www.dev-news.ga'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'dev-news.ga' ) {
        rewrite ^ https://www.$host$request_uri permanent;
      }
spec:
  rules:
    - host: 'dev-news.ga'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 8080
    - host: 'www.dev-news.ga'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 8080
    - host: 'api.dev-news.ga'
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 8080
    - host: 'cdn.dev-news.ga'
      http:
        paths:
          - backend:
              serviceName: cdn
              servicePort: 8080
    - host: 'kibana.dev-news.ga'
      http:
        paths:
          - backend:
              serviceName: elk
              servicePort: 5601
