apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: virtual-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: 'https://www.devnews.ga'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'devnews.ga' ) {
        rewrite ^ https://www.$host$request_uri permanent;
      }
spec:
  rules:
    - host: 'devnews.ga'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: frontend-http
    - host: 'www.devnews.ga'
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: frontend-http
    - host: 'api.devnews.ga'
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: backend-http
    - host: 'cdn.devnews.ga'
      http:
        paths:
          - backend:
              serviceName: cdn
              servicePort: cdn-http
    - host: 'kibana.devnews.ga'
      http:
        paths:
          - backend:
              serviceName: elk
              servicePort: kibana-http
